<!--
SPDX-FileCopyrightText: 2026 Neptuwunium <ada@chronovore.dev>

SPDX-License-Identifier: EUPL-1.2
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Feldspar\Feldspar.csproj" />
  </ItemGroup>

</Project>
